# Generated by Django 3.0.8 on 2020-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_library_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='sfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='sfile/pdf')),
            ],
        ),
    ]
