# Generated by Django 3.0.8 on 2020-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
