# Generated by Django 3.0.8 on 2020-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extendeduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='uname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
